name: build-and-deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python 3.10 + нужные версии без JAX-проблем
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install converter
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow==2.13.1 tensorflowjs==3.21.0 h5py

      - name: Convert Keras -> TFJS
        run: |
          python - << 'PY'
          import os, tensorflow as tf, tensorflowjs as tfjs
          src = "model_final.keras"  # если у тебя best_model.h5 — замени здесь
          out = "site/web_model"
          os.makedirs(out, exist_ok=True)
          m = tf.keras.models.load_model(src, compile=False)
          tfjs.converters.save_keras_model(m, out)
          print("OK ->", out)
          PY

      - name: Prepare site
        run: |
          mkdir -p site
          cp class_mapping.json site/
          # Если index.html лежит в корне — скопируем:
          cp index.html site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4